name: sign_language_mnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=23.3
  - pandas=2.1.1
  - numpy=1.26.4
  - matplotlib=3.8.1
  - seaborn=0.12.2
  - scikit-learn=1.3.2
  - tensorflow=2.13.0
  - keras=2.13.1
  - pip:
      - kagglehub==0.1.8
